#!/usr/bin/env node
// SessionStart hook: ignite machine mode.
// Detects per-repo state and hands the model a single instruction: invoke the
// `drill` skill. The skill owns the playbook (caveman comms, bootstrap when
// unoiled, drill mode when oiled). This hook only gathers state and emits
// additionalContext. It never blocks or errors the session.
//
// Disable: remove this hook from hooks.json, or tell the agent "stop caveman".

import { existsSync, writeFileSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// This file lives at <pluginRoot>/.claude/hooks/ignite.mjs and runs from inside the
// plugin payload, so its own location is the one always-correct source of the plugin
// root — no reliance on ${CLAUDE_PLUGIN_ROOT} expansion or a git fallback (both of
// which resolve to the wrong place once the machine is installed into another repo).
const PLUGIN_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");

// Write the resolved machine paths to /.machine/ENV.md — valid markdown AND a
// source-able shell file (# lines are headers and comments). Skills/agents read
// MACHINE_MINE etc. from here instead of guessing the kit location.
function writeEnv(projectDir) {
  const q = (p) => JSON.stringify(p);
  const body = [
    "# Machine environment — AUTO-GENERATED by .claude/hooks/ignite.mjs (SessionStart). Do not edit.",
    "# Gitignored: paths are per-install. `source` this file, or read a value, to locate machine assets.",
    "# Use these instead of expanding ${CLAUDE_PLUGIN_ROOT} (which does not expand in skill/agent prose).",
    `export MACHINE_PLUGIN_ROOT=${q(PLUGIN_ROOT)}`,
    `export MACHINE_PROJECT_DIR=${q(projectDir)}`,
    `export MACHINE_MINE=${q(join(PLUGIN_ROOT, "mine"))}`,
    `export MACHINE_MESH=${q(join(PLUGIN_ROOT, "mesh"))}`,
    "",
  ].join("\n");
  try {
    writeFileSync(join(projectDir, ".machine", "ENV.md"), body);
  } catch {
    // Best-effort: never block the session over the env cache.
  }
}

// The live roster lives in the hub (claims + board), not on disk. This hook does not
// scan a ledger directory; the drill rebuilds the footer from the hub on entry.

try {
  const root = process.env.CLAUDE_PROJECT_DIR || process.cwd();
  const machineReady = existsSync(join(root, ".machine"));

  if (machineReady) writeEnv(root);

  const lines = [
    "Caveman comm mode is ON by default this session.",
    "Invoke the `drill` skill now to bring up machine mode and follow it.",
    machineReady
      ? "Machine state: OILED (/.machine present)."
      : "Machine state: NOT OILED (/.machine absent) — drill will run bring-up (bootstrap + /oil) before driving.",
  ];

  if (machineReady) {
    lines.push(
      "On entry, rebuild the live roster from the hub (mcp__hub__roster + " +
        "mcp__hub__claims) and project it onto the board. Nothing auto-fires; await " +
        "user commands.",
    );
  }

  process.stdout.write(
    JSON.stringify({
      hookSpecificOutput: {
        hookEventName: "SessionStart",
        additionalContext: lines.join("\n"),
      },
    }),
  );
} catch {
  // Any unexpected failure degrades to silence.
  process.exit(0);
}
