#!/usr/bin/env bash
# machine — dependency bootstrap
#
# Installs and verifies everything the machine depends on, in one pass:
#   kern         memory daemon          (release installer, cargo fallback)
#   mesh         coordination daemon    (cargo install --path mesh)
#   git-fs       companion plugin       (claude plugin install)
#   context-mode vendored MCP server    (npx on demand; needs Node >=22.5.0)
#   context7     vendored MCP server    (needs CONTEXT7_API_KEY)
#   pdf-reader   vendored MCP server    (npx on demand)
#   taskboard    addon: kanban MCP+web  (build from source; needs Go 1.24 + Node 22)
#
# taskboard is an optional addon, not a core daemon: if Go or Node is missing it
# warns and skips (board projection disabled this session) — it never aborts the run.
#
# Idempotent: already-satisfied dependencies are skipped. Safe to re-run.
# Usage: scripts/bootstrap.sh   (or: just bootstrap)

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KERN_INSTALLER="https://raw.githubusercontent.com/yesitsfebreeze/relay-kern/master/install.sh"

# --- output helpers ---------------------------------------------------------
bold=$(tput bold 2>/dev/null || true); dim=$(tput dim 2>/dev/null || true)
red=$(tput setaf 1 2>/dev/null || true); grn=$(tput setaf 2 2>/dev/null || true)
ylw=$(tput setaf 3 2>/dev/null || true); rst=$(tput sgr0 2>/dev/null || true)

declare -a SUMMARY
ok()   { echo "  ${grn}ok${rst}    $1";   SUMMARY+=("ok|$1"); }
did()  { echo "  ${grn}done${rst}  $1";   SUMMARY+=("done|$1"); }
warn() { echo "  ${ylw}warn${rst}  $1";   SUMMARY+=("warn|$1"); }
fail() { echo "  ${red}fail${rst}  $1";   SUMMARY+=("fail|$1"); }
head() { echo; echo "${bold}$1${rst}"; }

have() { command -v "$1" >/dev/null 2>&1; }

# Node >= 22.5.0 ?
node_ok() {
  have node || return 1
  local v major minor
  v="$(node -v 2>/dev/null | sed 's/^v//')"
  major="${v%%.*}"; minor="$(echo "$v" | cut -d. -f2)"
  [ "${major:-0}" -gt 22 ] && return 0
  [ "${major:-0}" -eq 22 ] && [ "${minor:-0}" -ge 5 ] && return 0
  return 1
}

# ~/.local/bin — user-owned; must be on PATH for the links/shim below to win.
LOCAL_BIN="${HOME}/.local/bin"
on_path() { case ":$PATH:" in *":$1:"*) return 0;; *) return 1;; esac; }

# Echo a node binary's version if it is >= 22.5.0, else return non-zero.
node_bin_ok() {
  local bin="$1" v major minor
  [ -x "$bin" ] || return 1
  v="$("$bin" -v 2>/dev/null | sed 's/^v//')" || return 1
  major="${v%%.*}"; minor="$(echo "$v" | cut -d. -f2)"
  { [ "${major:-0}" -gt 22 ]; } || { [ "${major:-0}" -eq 22 ] && [ "${minor:-0}" -ge 5 ]; } || return 1
  echo "$v"
}

# Find the newest Node >=22.5.0 already installed under nvm/fnm. Echo its bin dir.
find_modern_node() {
  local best="" bestv="" cand v
  for cand in \
    "$HOME"/.nvm/versions/node/v*/bin/node \
    "$HOME"/.local/share/fnm/node-versions/*/installation/bin/node \
    "$HOME"/.fnm/node-versions/*/installation/bin/node; do
    [ -x "$cand" ] || continue
    v="$(node_bin_ok "$cand")" || continue
    if [ -z "$bestv" ] || [ "$(printf '%s\n%s\n' "$bestv" "$v" | sort -V | tail -1)" = "$v" ]; then
      bestv="$v"; best="$(dirname "$cand")"
    fi
  done
  [ -n "$best" ] && echo "$best"
}

# Ensure the harness resolves Node >=22.5.0. If system Node is too old but a modern
# Node exists under nvm/fnm, link node/npm/npx into ~/.local/bin (idempotent).
ensure_node() {
  head "Node (>=22.5.0 for context-mode / pdf-reader)"
  if node_ok; then ok "Node $(node -v) satisfies >=22.5.0"; return; fi
  local bindir; bindir="$(find_modern_node)"
  if [ -z "$bindir" ]; then
    warn "Node $(node -v 2>/dev/null || echo 'missing') < 22.5.0 and no newer Node found — install one (e.g. nvm install 22)"; return
  fi
  if ! on_path "$LOCAL_BIN"; then
    warn "modern Node at $bindir but $LOCAL_BIN not on PATH — add it to PATH, then re-run"; return
  fi
  mkdir -p "$LOCAL_BIN"
  ln -sf "$bindir/node" "$LOCAL_BIN/node"
  ln -sf "$bindir/npm"  "$LOCAL_BIN/npm"
  ln -sf "$bindir/npx"  "$LOCAL_BIN/npx"
  did "linked Node $("$bindir/node" -v) into $LOCAL_BIN (restart Claude to apply)"
}

# Create the git-fs-mcp shim the git-fs plugin expects. The plugin is git-cloned
# (no npm bin link), so its declared `git-fs-mcp` binary never lands on PATH; point
# a shim at the newest cached plugin server. Idempotent.
ensure_gitfs_shim() {
  head "git-fs-mcp (MCP launcher shim)"
  if have git-fs-mcp && [ ! -L "$LOCAL_BIN/git-fs-mcp" ]; then
    ok "git-fs-mcp already on PATH ($(command -v git-fs-mcp))"; return
  fi
  local base="$HOME/.claude/plugins/cache/git-fs/git-fs"
  if [ ! -d "$base" ]; then
    warn "git-fs plugin not installed yet — re-run after /plugin install git-fs@git-fs to create the shim"; return
  fi
  if ! on_path "$LOCAL_BIN"; then
    warn "$LOCAL_BIN not on PATH — cannot place git-fs-mcp shim; add it and re-run"; return
  fi
  mkdir -p "$LOCAL_BIN"
  cat > "$LOCAL_BIN/git-fs-mcp" <<'SHIM'
#!/usr/bin/env bash
# Auto-generated by machine bootstrap. Launches the git-fs plugin's MCP server
# (newest cached version with dist/mcp.js). Safe to delete; bootstrap recreates it.
set -euo pipefail
base="$HOME/.claude/plugins/cache/git-fs/git-fs"
ver="$(ls -1 "$base" 2>/dev/null | sort -V | tac | while read -r v; do [ -f "$base/$v/dist/mcp.js" ] && { echo "$v"; break; }; done)"
[ -n "${ver:-}" ] || { echo "git-fs-mcp: no dist/mcp.js under $base" >&2; exit 127; }
exec node "$base/$ver/dist/mcp.js" "$@"
SHIM
  chmod +x "$LOCAL_BIN/git-fs-mcp"
  did "git-fs-mcp shim written to $LOCAL_BIN (restart Claude to apply)"
}

# --- kern -------------------------------------------------------------------
install_kern() {
  head "kern (memory daemon)"
  if have kern; then ok "kern present ($(command -v kern))"; return; fi
  if have curl; then
    echo "  installing via release installer..."
    if curl -fsSL "$KERN_INSTALLER" | sh; then did "kern installed"; return; fi
    warn "release installer failed"
  fi
  if have cargo; then
    echo "  falling back to cargo..."
    if cargo install --git https://github.com/yesitsfebreeze/relay-kern kern; then
      did "kern installed (cargo)"; return
    fi
  fi
  fail "kern not installed — see https://github.com/yesitsfebreeze/kern"
}

# --- mesh -------------------------------------------------------------------
install_mesh() {
  head "mesh (coordination daemon)"
  if have mesh; then ok "mesh present ($(command -v mesh))"; return; fi
  if [ ! -d "$REPO_ROOT/mesh" ]; then
    fail "mesh source not found at $REPO_ROOT/mesh — clone the machine repo to build it"; return
  fi
  if ! have cargo; then
    fail "cargo (Rust toolchain) required to build mesh — https://rustup.rs"; return
  fi
  echo "  building from $REPO_ROOT/mesh..."
  if cargo install --path "$REPO_ROOT/mesh"; then did "mesh installed"; else fail "mesh build failed"; fi
}

# --- git-fs plugin ----------------------------------------------------------
install_gitfs() {
  head "git-fs (companion plugin)"
  if ! have claude; then warn "claude CLI not found — install git-fs manually: /plugin install git-fs@git-fs"; return; fi
  # The claude CLI cannot be nested inside a running Claude Code session
  # (sandbox isolation). Defer to the in-session /plugin commands instead.
  if [ -n "${CLAUDECODE:-}" ]; then
    warn "in a Claude Code session — run in-session: /plugin marketplace add yesitsfebreeze/git-fs then /plugin install git-fs@git-fs"
    return
  fi
  if claude plugin list 2>/dev/null | grep -qi "git-fs"; then ok "git-fs plugin already installed"; return; fi
  echo "  adding marketplace + installing..."
  claude plugin marketplace add yesitsfebreeze/git-fs >/dev/null 2>&1 || true
  if claude plugin install git-fs@git-fs >/dev/null 2>&1; then
    did "git-fs installed (run /reload-plugins to apply)"
  else
    warn "git-fs install failed — try: claude plugin install git-fs@git-fs"
  fi
}

# --- context7 + pdf-reader (vendored) --------------------------------------
check_others() {
  head "context7 + pdf-reader (vendored MCP)"
  if [ -n "${CONTEXT7_API_KEY:-}" ]; then ok "CONTEXT7_API_KEY is set"; else warn "CONTEXT7_API_KEY unset — context7 docs server will be unauthenticated"; fi
  if have npx; then ok "npx present — pdf-reader fetches on demand"; else warn "npx not found — pdf-reader needs Node.js"; fi
}

# --- graphify pre-push hook (repo-local; never ships) ----------------------
install_graphify() {
  head "graphify pre-push hook"
  local hook=".git/hooks/pre-push"
  if [ ! -d .git ]; then warn "no .git dir — skipping graphify hook"; return; fi
  cat > "$hook" <<'HOOK'
#!/usr/bin/env bash
# machine: graphify — rebuild the repo capability graph on every push.
# Repo-local, never travels (lives in .git/, not the plugin payload).
# NEVER blocks the push: any failure is a warning, exit is always 0.
root="$(git rev-parse --show-toplevel 2>/dev/null)" || exit 0
if command -v node >/dev/null 2>&1; then
  node "$root/scripts/graphify.mjs" || echo "graphify: skipped (non-fatal)" >&2
fi
exit 0
HOOK
  chmod +x "$hook"
  if have node; then node scripts/graphify.mjs >/dev/null 2>&1 && ok "graphify hook installed + initial graph built (.machine/graph.json)" || ok "graphify hook installed (initial build deferred)"; else warn "node not found — graphify hook installed but cannot run until node is present"; fi
}

# --- taskboard (addon: local kanban MCP + web) -----------------------------
# Provisioning is prebuilt-first: upstream ships statically-linked release binaries
# with the web frontend embedded, so the common path needs neither Go nor Node. The
# source build is a fallback only when the download fails. Both paths pin a version
# (never track latest); bump TASKBOARD_VERSION / TASKBOARD_REF deliberately to upgrade.
# Rollback: remove the plugin.json `taskboard` mcpServers entry and
# mine/skills/taskboard/; optionally `taskboard stop`; the SQLite DB at
# ~/.config/taskboard/taskboard.db is left untouched.
TASKBOARD_VERSION="v0.6.0"   # pinned release tag for the prebuilt binary
TASKBOARD_REPO="https://github.com/tcarac/taskboard"
TASKBOARD_REF="$TASKBOARD_VERSION"   # source-build fallback checks out this ref
TASKBOARD_PORT="3010"

# Go >= 1.24 ?  (taskboard go.mod requires 1.24.0)
go_ok() {
  have go || return 1
  local v major minor
  v="$(go env GOVERSION 2>/dev/null | sed 's/^go//')"
  [ -n "$v" ] || v="$(go version 2>/dev/null | sed -n 's/.*go\([0-9.]*\).*/\1/p')"
  major="${v%%.*}"; minor="$(echo "$v" | cut -d. -f2)"
  [ "${major:-0}" -gt 1 ] && return 0
  [ "${major:-0}" -eq 1 ] && [ "${minor:-0}" -ge 24 ] && return 0
  return 1
}

# Poll the pidfile + web API until the daemon is listening (bounded). daemonize
# returns before the server binds, so confirm readiness before declaring it up.
taskboard_ready() {
  local pidfile="${XDG_CONFIG_HOME:-$HOME/.config}/taskboard/taskboard.pid"
  local i
  for i in 1 2 3 4 5 6 7 8 9 10; do
    if [ -f "$pidfile" ] && have curl \
       && curl -fsS "http://localhost:${TASKBOARD_PORT}/api/board" >/dev/null 2>&1; then
      return 0
    fi
    sleep 1
  done
  return 1
}

# Map uname to the release asset's os-arch token (echo it), else return non-zero.
taskboard_platform() {
  local os arch
  case "$(uname -s)" in
    Linux)  os="linux" ;;
    Darwin) os="darwin" ;;
    *) return 1 ;;
  esac
  case "$(uname -m)" in
    x86_64|amd64)  arch="amd64" ;;
    arm64|aarch64) arch="arm64" ;;
    *) return 1 ;;
  esac
  echo "${os}-${arch}"
}

# Download + install the pinned prebuilt binary into $LOCAL_BIN. Returns non-zero
# on any failure so the caller can fall back to a source build.
taskboard_install_prebuilt() {
  have curl || return 1
  have tar  || return 1
  local plat; plat="$(taskboard_platform)" || return 1
  local url="$TASKBOARD_REPO/releases/download/$TASKBOARD_VERSION/taskboard-${plat}.tar.gz"
  local tmp; tmp="$(mktemp -d)" || return 1
  echo "  downloading taskboard $TASKBOARD_VERSION ($plat) ..."
  if ! curl -fsSL "$url" -o "$tmp/taskboard.tar.gz" 2>/dev/null; then
    rm -rf "$tmp"; return 1
  fi
  if ! tar -xzf "$tmp/taskboard.tar.gz" -C "$tmp" 2>/dev/null; then
    rm -rf "$tmp"; return 1
  fi
  # The archive may hold the binary as taskboard-<plat> or plain taskboard. Find the
  # first match without piping through `head` — bootstrap.sh defines a `head()`
  # function that shadows the coreutils binary, so a `| head` here would misbehave.
  local bin="" cand
  while IFS= read -r cand; do bin="$cand"; break; done < <(
    find "$tmp" -type f \( -name 'taskboard' -o -name "taskboard-${plat}" \) 2>/dev/null
  )
  if [ -z "$bin" ]; then rm -rf "$tmp"; return 1; fi
  mkdir -p "$LOCAL_BIN"
  if ! install -m 0755 "$bin" "$LOCAL_BIN/taskboard" 2>/dev/null; then
    cp "$bin" "$LOCAL_BIN/taskboard" && chmod +x "$LOCAL_BIN/taskboard" || { rm -rf "$tmp"; return 1; }
  fi
  rm -rf "$tmp"
  return 0
}

# Source build (fallback only). The //go:embed web/dist makes the frontend a hard
# build dependency, so a bare `go install` cannot work — needs Go + Node + make + git.
taskboard_build_source() {
  go_ok || return 1
  node_ok || return 1
  have make || return 1
  have git  || return 1
  local src="${XDG_CACHE_HOME:-$HOME/.cache}/machine/taskboard"
  echo "  building taskboard from $TASKBOARD_REPO @ $TASKBOARD_REF ..."
  if [ -d "$src/.git" ]; then
    git -C "$src" fetch --quiet origin 2>/dev/null || true
  else
    mkdir -p "$(dirname "$src")"
    git clone --quiet "$TASKBOARD_REPO" "$src" 2>/dev/null || return 1
  fi
  git -C "$src" checkout --quiet "$TASKBOARD_REF" 2>/dev/null || return 1
  ( cd "$src" && make build >/dev/null 2>&1 ) || return 1
  mkdir -p "$LOCAL_BIN"
  cp "$src/taskboard" "$LOCAL_BIN/taskboard" 2>/dev/null || return 1
  chmod +x "$LOCAL_BIN/taskboard"
  return 0
}

install_taskboard() {
  head "taskboard (addon: kanban MCP + web board)"

  # 1. Already installed → skip straight to the daemon.
  if have taskboard; then
    ok "taskboard present ($(command -v taskboard))"
  else
    # 2. Primary: pinned prebuilt binary (no Go, no Node).
    # 3. Fallback: source build, only if the download failed.
    local how=""
    if taskboard_install_prebuilt; then
      how="prebuilt $TASKBOARD_VERSION"
    elif taskboard_build_source; then
      how="source build"
    else
      warn "taskboard install skipped (prebuilt download failed; source build needs Go 1.24 + Node 22) — board projection off"
      return
    fi
    if ! on_path "$LOCAL_BIN"; then
      warn "taskboard installed to $LOCAL_BIN but it is not on PATH — add it and re-run"
      return
    fi
    if ! have taskboard; then
      warn "taskboard installed to $LOCAL_BIN but not resolvable on PATH"
      return
    fi
    if ! taskboard --help >/dev/null 2>&1; then
      warn "taskboard binary installed but does not run — board projection off"
      return
    fi
    did "taskboard installed via $how ($LOCAL_BIN/taskboard)"
  fi

  # 4. Daemon start ("one server if not up"). `taskboard start` daemonizes and
  #    refuses a double-start, so treat "already running" as ok.
  local out
  out="$(taskboard start 2>&1)" || true
  if printf '%s' "$out" | grep -qi 'already running'; then
    ok "taskboard daemon already running (:$TASKBOARD_PORT)"
  elif taskboard_ready; then
    did "taskboard daemon up (http://localhost:$TASKBOARD_PORT)"
  else
    warn "taskboard daemon did not become ready on :$TASKBOARD_PORT — MCP card ops still work without the web UI"
  fi
}

# --- run --------------------------------------------------------------------
echo "${bold}machine bootstrap${rst} ${dim}(idempotent — re-run anytime)${rst}"
install_kern
install_mesh
install_gitfs
ensure_gitfs_shim
ensure_node
check_others
install_taskboard
install_graphify

head "summary"
fails=0; warns=0
for row in "${SUMMARY[@]}"; do
  status="${row%%|*}"; msg="${row#*|}"
  case "$status" in
    fail) echo "  ${red}x${rst} $msg"; fails=$((fails+1));;
    warn) echo "  ${ylw}!${rst} $msg"; warns=$((warns+1));;
    *)    echo "  ${grn}+${rst} $msg";;
  esac
done
echo
if [ "$fails" -gt 0 ]; then
  echo "${red}${bold}$fails dependency/dependencies missing.${rst} Resolve the items above, then re-run."
  exit 1
fi
[ "$warns" -gt 0 ] && echo "${ylw}Bootstrap complete with $warns warning(s).${rst}" || echo "${grn}${bold}All dependencies satisfied.${rst}"
echo "${dim}Restart Claude Code (or /reload-plugins) so MCP servers and plugins load.${rst}"
exit 0
